expiry-period-format: '&e[Expiry Time: %value%]'
expiry-date-format: '&e[Expiry Date: %value%]'
item-expired: '&c&l[!] Item is expired'
item-expired-placement: action-bar
remove-expired-item: true
expired-item-removed: '&cRemoved %amount% expired items'
replaced-item-dropped: '&c[!] Some items were dropped on the ground'
unit-format:
  second: '%d second'
  minute: '%d minute'
  hour: '%d hour'
  day: '%d day'
  seconds: '%d seconds'
  minutes: '%d minutes'
  hours: '%d hours'
  days: '%d days'
item-check-interval: 5
replace-expiry-period: true
date-format: dd/MM/yyyy
force-update-inventory: false
enable-bypass-permission: false
expired-type-replace:
  CONSUMABLE:
    - type: bukkit
      id: rotten_flesh
      amount: 1
expired-item-replace:
  DRAGON_CHESTPLATE:
    - type: bukkit
      id: iron_ingot
      amount: 2
    - type: MATERIAL
      id: RARE_DIAMOND
      amount: 1
debug-level: 0
