expiry-period-format: "&e[Expiry Time: %value%]"
expiry-date-format: "&e[Expiry Date: %value%]"
item-expired: "&c&l[!] Item is expired"
item-expired-placement: action-bar # action-bar, chat, off
remove-expired-item: true
expired-item-removed: "&cRemoved %amount% expired items"
unit-format:
  second: "%d second"
  minute: "%d minute"
  hour: "%d hour"
  day: "%d day"
  seconds: "%d seconds"
  minutes: "%d minutes"
  hours: "%d hours"
  days: "%d days"
item-check-interval: 5 # in seconds
replace-expiry-period: true # replace expiry period with expiry date instead of keeping both stats
